# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: VisualPDE Canary
email: hello@visualpde.com
description: >- # this means to ignore newlines until "baseurl:"
  Interactive solutions of partial differential equations, live on your device
#baseurl: "/site" # the subpath of your site, e.g. /blog
url: "https://canary.visualpde.com" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: pecnut
#github_username:  Pecnut
google_analytics: G-ZDK91GRY6Y

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Nav bar
header_pages:
  - about.md
  - user-guide.md
  - contact.md

collections:
  basic-pdes:
    output: true
    title: Introductory PDEs
  art-pdes:
    output: true
    title: Art of PDEs
  mathematical-biology:
    output: true
    title: Mathematical biology
  nonlinear-physics:
    output: true
    title: Nonlinear physics
  user-guide:
    output: true
    title: User guide
  visual-stories:
    output: true
    title: Visual stories
  numerical-methods:
    output: true
    title: Numerical methods
  research:
    output: true
    title: Research
  demos:
    output: true
    title: Demos

defaults:
  - scope:
      path: ""
      type: "mathematical-biology" # a collection in your site, in plural form
    values:
      thumbnail: "/assets/images/squirrel.webp"
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
