// presets.js

export function getPreset(id) {
  let options;
  switch (id) {
    case "chemicalBasisOfMorphogenesis":
      options = {
        boundaryConditionsU: "periodic",
        boundaryConditionsV: "periodic",
        brushValue: "1",
        brushRadius: 1 / 20,
        clearValueU: "0",
        clearValueV: "0",
        colourmap: "turbo",
        diffusionUStr: "0.0000042",
        diffusionVStr: "0.0002",
        domainScale: 1,
        dt: 0.001,
        fixRandSeed: false,
        imagePath: "./images/chemicalBasisOfMorphogenesis.png",
        maxColourValue: 2.3,
        minColourValue: 0.0,
        numSpecies: 2,
        numTimestepsPerFrame: 8,
        preset: "chemicalBasisOfMorphogenesis",
        renderSize: 652,
        reactionStrU: "(1-T) - u + u^2*v",
        reactionStrV: "1 - u^2*v",
        setTimestepForStability: true,
        showAllOptionsOverride: true,
        spatialStep: 0.002,
        squareCanvas: true,
        typeOfBrush: "circle",
        whatToDraw: "u",
        whatToPlot: "u",
      };
      break;
    case "localisedPatterns":
      options = {
        boundaryConditionsU: "periodic",
        boundaryConditionsV: "periodic",
        brushValue: "9",
        brushRadius: 0.1,
        clearValueU: "1",
        clearValueV: "0.99",
        colourmap: "turbo",
        diffusionUStr: "0.0010",
        diffusionVStr: "0.5",
        domainScale: 10,
        dt: 0.000625,
        fixRandSeed: false,
        kineticParams: "",
        maxColourValue: 9.0,
        minColourValue: 2.0,
        numSpecies: 2,
        numTimestepsPerFrame: 200,
        preset: "localisedPatterns",
        renderSize: 700,
        reactionStrU: "(1+tanh(1*((x-5)*(x-5)+(y-5)*(y-5)-20)))-u+u^2*v",
        reactionStrV: "0.99 - u^2*v",
        setTimestepForStability: true,
        spatialStep: 0.05,
        squareCanvas: true,
        typeOfBrush: "circle",
        whatToDraw: "u",
        whatToPlot: "u",
      };
      break;
    case "thresholdSimulation":
      options = {
        boundaryConditionsU: "noflux",
        brushValue: "1",
        brushRadius: 0.005,
        clearValueU: "0",
        colourmap: "turbo",
        diffusionUStr: "0.0001",
        dirichletU: "0",
        domainScale: 1,
        dt: 0.002,
        fixRandSeed: false,
        kineticParams: "",
        maxColourValue: 1.0,
        minColourValue: 0.0,
        numSpecies: 1,
        numTimestepsPerFrame: 200,
        preset: "thresholdSimulation",
        renderSize: 700,
        reactionStrU: "u*(1-u)*(u-0.4)",
        robinStrU: "0",
        spatialStep: 0.005,
        squareCanvas: false,
        typeOfBrush: "circle",
        whatToDraw: "u",
        whatToPlot: "u",
      };
      break;
    case "harshEnvironment":
      options = {
        boundaryConditionsU: "dirichlet",
        brushValue: "1",
        brushRadius: 1 / 20,
        clearValueU: "0",
        colourmap: "turbo",
        diffusionUStr: "0.0001",
        dirichletU: "0",
        domainScale: 1,
        dt: 0.00006,
        fixRandSeed: false,
        kineticParams: "",
        maxColourValue: 1.0,
        minColourValue: 0.0,
        numSpecies: 1,
        numTimestepsPerFrame: 200,
        preset: "harshEnvironment",
        renderSize: 700,
        reactionStrU: "u*(1-u)",
        robinStrU: "0",
        spatialStep: 0.005,
        squareCanvas: false,
        typeOfBrush: "circle",
        whatToDraw: "u",
        whatToPlot: "u",
      };
      break;
    case "travellingWave":
      options = {
        boundaryConditionsU: "noflux",
        brushValue: "1",
        brushRadius: 1 / 20,
        clearValueU: "0",
        colourmap: "turbo",
        diffusionUStr: "0.000001",
        dirichletU: "0",
        domainScale: 1,
        dt: 0.002,
        fixRandSeed: false,
        kineticParams: "",
        maxColourValue: 1.0,
        minColourValue: 0.0,
        numSpecies: 1,
        numTimestepsPerFrame: 200,
        preset: "travellingWave",
        renderSize: 700,
        reactionStrU: "u*(1-u)",
        robinStrU: "0",
        spatialStep: 0.005,
        squareCanvas: false,
        typeOfBrush: "vline",
        whatToDraw: "u",
        whatToPlot: "u",
      };
      break;
    case "Alan":
      options = {
        boundaryConditionsU: "periodic",
        boundaryConditionsV: "periodic",
        brushValue: "1",
        brushRadius: 1 / 20,
        clearValueU: "0",
        clearValueV: "0",
        colourmap: "turbo",
        diffusionUStr: "0.0000042",
        diffusionVStr: "0.0002",
        domainScale: 1,
        dt: 0.001,
        fixRandSeed: false,
        imagePath: "./images/Alan.png",
        maxColourValue: 2.3,
        minColourValue: 0.0,
        numSpecies: 2,
        numTimestepsPerFrame: 200,
        preset: "Alan",
        renderSize: 652,
        reactionStrU: "(1-T) - u + u^2*v",
        reactionStrV: "1 - u^2*v",
        setTimestepForStability: false,
        showAllOptionsOverride: true,
        spatialStep: 0.002,
        squareCanvas: true,
        typeOfBrush: "circle",
        whatToDraw: "u",
        whatToPlot: "u",
      };
      break;
    case "heatEquation":
      options = {
        boundaryConditionsU: "noflux",
        brushValue: "1",
        brushRadius: 0.1,
        clearValueU: "0",
        colourmap: "turbo",
        diffusionUStr: "0.00001",
        dirichletU: "0",
        domainScale: 1,
        dt: 0.01,
        maxColourValue: 1.0,
        minColourValue: 0.0,
        numSpecies: 1,
        numTimestepsPerFrame: 100,
        onlyExposeOptions: [],
        preset: "heatEquation",
        renderSize: 256,
        reactionStrU: "0",
        robinStrU: "0",
        setTimestepForStability: false,
        spatialStep: 0.005,
        squareCanvas: false,
        typeOfBrush: "circle",
        whatToDraw: "u",
        whatToPlot: "u",
      };
      break;
    case "subcriticalGS":
      options = {
        boundaryConditionsU: "periodic",
        boundaryConditionsV: "periodic",
        brushValue: "1",
        brushRadius: 1 / 20,
        clearValueU: "0",
        clearValueV: "0",
        colourmap: "turbo",
        dirichletU: "0",
        dirichletV: "0",
        domainScale: 1,
        dt: 0.1,
        maxColourValue: 1.0,
        minColourValue: 0.0,
        numSpecies: 2,
        numTimestepsPerFrame: 100,
        preset: "subcriticalGS",
        renderSize: 256,
        reactionStrU: "-u*v^2 + 0.037*(1.0 - u)",
        reactionStrV: "u*v^2 - (0.037+0.06)*v",
        robinStrU: "0",
        robinStrV: "0",
        setTimestepForStability: false,
        spatialStep: 1 / 200,
        squareCanvas: false,
        typeOfBrush: "circle",
        whatToDraw: "v",
        whatToPlot: "v",
      };
      break;
    default:
      options = {
        boundaryConditionsU: "periodic",
        boundaryConditionsV: "periodic",
        boundaryConditionsW: "periodic",
        brushValue: "1",
        brushRadius: 1 / 20,
        clearValueU: "0",
        clearValueV: "0",
        clearValueW: "0",
        colourmap: "turbo",
        diffusionUStr: "0.000004",
        diffusionVStr: "0.000002",
        diffusionWStr: "0.000002",
        dirichletU: "0",
        dirichletV: "0",
        dirichletW: "0",
        domainScale: 1,
        dt: 0.1,
        fixRandSeed: false,
        imagePath: "./images/Alan.png",
        kineticParams: "",
        maxColourValue: 1.0,
        minColourValue: 0.0,
        numSpecies: 2,
        numTimestepsPerFrame: 100,
        onlyExposeOptions: [],
        preset: "default",
        renderSize: 256,
        reactionStrU: "-u*v^2 + 0.037*(1.0 - u)",
        reactionStrV: "u*v^2 - (0.037+0.06)*v",
        reactionStrW: "u*v^2 - (0.037+0.06)*v",
        robinStrU: "0",
        robinStrV: "0",
        robinStrW: "0",
        setTimestepForStability: false,
        showAllOptionsOverride: false,
        spatialStep: 1 / 200,
        squareCanvas: false,
        typeOfBrush: "circle",
        whatToDraw: "v",
        whatToPlot: "v",
      };
  }
  return options;
}
