name: build-and-deploy
on: 
  push:
    branches:
      - main

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v3
      - name : Setup node
        uses: actions/setup-node@v3
      - name: Build doclist
        run: |
          npm install
          node build_index.js
        working-directory: assets/js/build_index
      - name: Run terser on sim/scripts
        run: |
          npm install -g terser
          find . -name "*.js" | while read file; do
            terser --compress --mangle --module --output "$file" -- "$file"
          done
        working-directory: ./sim/scripts/
      - name: Webpack simulation scripts
        run: |
          npm install webpack webpack-cli
          npx webpack
        working-directory: ./sim/scripts/RD
      - name: Minify all CSS
        run: |
          npm install clean-css-cli -g
          find . -name "*.css" | while read file; do
            cleancss -o "$file" "$file"
          done
      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./
          destination: ./_site
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2

  # Deployment job
  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
